# Generated by Django 3.2.6 on 2021-08-23 18:42

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('is_researcher', models.BooleanField()),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Study_Subject',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Not disclosed')], default='N', max_length=2)),
                ('is_researcher', models.BooleanField()),
                ('bank_account', models.TextField()),
                ('age', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Research_Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting', models.CharField(choices=[('On', 'Online'), ('Off', 'Offline')], default='On', max_length=4)),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('exp_type', models.CharField(max_length=400)),
                ('collected_data', models.TextField()),
                ('reward', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField()),
                ('participant_number', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('time', models.TextField()),
                ('location', models.CharField(max_length=1000)),
                ('additional_info', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicants', models.ManyToManyField(blank=True, related_name='my_applications', to='api_app.Study_Subject')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_posts', to='api_app.researcher')),
                ('confirmed_applicants', models.ManyToManyField(blank=True, related_name='confirmend_applications', to='api_app.Study_Subject')),
                ('declined_applicants', models.ManyToManyField(blank=True, related_name='declined_applications', to='api_app.Study_Subject')),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to='api_app.Study_Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria1', models.PositiveIntegerField()),
                ('criteria2', models.PositiveIntegerField()),
                ('criteria3', models.PositiveIntegerField()),
                ('overall_rating', models.PositiveIntegerField()),
                ('rated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_ratings', to='api_app.study_subject')),
                ('rater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rated_applicants', to='api_app.researcher')),
            ],
        ),
    ]
