# Generated by Django 3.2.6 on 2021-10-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='study_subject',
            name='reputation',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
