# Generated by Django 3.2.6 on 2021-10-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_study_subject_reputation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study_subject',
            name='reputation',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
